<a href="https://colab.research.google.com/github/bhomik179/Experiment-14/blob/main/exp_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
 # EXPERIMENT - 14

# Data Binning and Data Formatting using Phyton

# Name: bhomik v keshi

# PRN: 25070123172

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product': ['Laptop', 'Mobile', 'Tablet', 'Headphones', 'Smartwatch', 'Camera'],
    'Price': [55000, 20000, 30000, 2000, 8000, 45000],
    'Units_Sold': [25, 60, 35, 80, 50, 15]
}

df=pd.DataFrame(data)
display(df)
print()
print()

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#Data Binning
bins1= [0, 10000,30000,60000]
labels1=['LOW','MEDIUM','HIGH']
df['Price_Category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)
display(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           HIGH
1      Mobile  20000          60         MEDIUM
2      Tablet  30000          35         MEDIUM
3  Headphones   2000          80            LOW
4  Smartwatch   8000          50            LOW
5      Camera  45000          15           HIGH

In [ ]:
bins2=[0,30,60,100]
labels2=['LOW','MEDIUM','HIGH']
df['Sales_Category']=pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
display(df)

      Product  Price  Units_Sold Price_Category Sales_Category
0      Laptop  55000          25           HIGH            LOW
1      Mobile  20000          60         MEDIUM         MEDIUM
2      Tablet  30000          35         MEDIUM         MEDIUM
3  Headphones   2000          80            LOW           HIGH
4  Smartwatch   8000          50            LOW         MEDIUM
5      Camera  45000          15           HIGH            LOW

In [ ]:
print(df.dtypes)
df['Units_Sold']=df['Units_Sold'].astype(float)

print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
dtype: object
Product             object
Price                int64
Units_Sold         float64
Price_Category    category
dtype: object

In [ ]:
#Convert text to uppercase
df['Product'] = df['Product'].str.upper()

print(df)

      Product  Price  Units_Sold Price_Category
0      LAPTOP  55000        25.0           HIGH
1      MOBILE  20000        60.0         MEDIUM
2      TABLET  30000        35.0         MEDIUM
3  HEADPHONES   2000        80.0            LOW
4  SMARTWATCH   8000        50.0            LOW
5      CAMERA  45000        15.0           HIGH

In [ ]:
#Rounding Values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category
0      LAPTOP  55000        25.0           HIGH
1      MOBILE  20000        60.0         MEDIUM
2      TABLET  30000        35.0         MEDIUM
3  HEADPHONES   2000        80.0            LOW
4  SMARTWATCH   8000        50.0            LOW
5      CAMERA  45000        15.0           HIGH

In [ ]:
#Additional operations
#Sort Data
sorted_df=df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category
3  HEADPHONES   2000        80.0            LOW
4  SMARTWATCH   8000        50.0            LOW
1      MOBILE  20000        60.0         MEDIUM
2      TABLET  30000        35.0         MEDIUM
5      CAMERA  45000        15.0           HIGH
0      LAPTOP  55000        25.0           HIGH

In [ ]:
#Additional operations
#Sort Data
sorted_df=df.sort_values(by='Price',ascending=False)
print(sorted_df)

      Product  Price  Units_Sold Price_Category
0      LAPTOP  55000        25.0           HIGH
5      CAMERA  45000        15.0           HIGH
2      TABLET  30000        35.0         MEDIUM
1      MOBILE  20000        60.0         MEDIUM
4  SMARTWATCH   8000        50.0            LOW
3  HEADPHONES   2000        80.0            LOW

In [ ]:
#Display Unique Values
unique_products=df['Price_Category'].unique()
print(unique_products)

['HIGH', 'MEDIUM', 'LOW']
Categories (3, object): ['LOW' < 'MEDIUM' < 'HIGH']

In [ ]:
import pandas as pd
import numpy as np

data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'],
'Order_Value':[250,450,120,600,300,150,500,220],
'Delivery_Time':[30,45,25,60,35,20,50,28],
'Distance_km':[5,8,3,10,6,2,9,4]
}

df = pd.DataFrame(data)

print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       O1          250             30            5
1       O2          450             45            8
2       O3          120             25            3
3       O4          600             60           10
4       O5          300             35            6
5       O6          150             20            2
6       O7          500             50            9
7       O8          220             28            4

In [ ]:
#Binning Order Value
bins = [0,200,400,700]
labels1 = ['LOW order','MEDIUM order','HIGH order']
df['Order_Value_Category'] = pd.cut(df['Order_Value'],bins=bins1,labels=labels1)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category
0       O1          250             30            5            LOW order
1       O2          450             45            8            LOW order
2       O3          120             25            3            LOW order
3       O4          600             60           10            LOW order
4       O5          300             35            6            LOW order
5       O6          150             20            2            LOW order
6       O7          500             50            9            LOW order
7       O8          220             28            4            LOW order

In [ ]:
#Count of categories
print(df['Order_Value_Category'].value_counts())
df

Order_Value_Category
LOW order       8
MEDIUM order    0
HIGH order      0
Name: count, dtype: int64

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category
0       O1          250             30            5            LOW order
1       O2          450             45            8            LOW order
2       O3          120             25            3            LOW order
3       O4          600             60           10            LOW order
4       O5          300             35            6            LOW order
5       O6          150             20            2            LOW order
6       O7          500             50            9            LOW order
7       O8          220             28            4            LOW order